# Generated by Django 5.2.13 on 2026-04-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_instructor_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='enrollment',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
